import * as os from 'os';

const mac = {
  Escape: '[Esc]',
  Digit1: '[1]',
  Digit2: '[2]',
  Digit3: '[3]',
  Digit4: '[4]',
  Digit5: '[5]',
  Digit6: '[6]',
  Digit7: '[7]',
  Digit8: '[8]',
  Digit9: '[9]',
  Digit0: '[0]',
  Minus: '[-]',
  Equal: '[=]',
  Backspace: '[Back]',
  Tab: '[Tab]',
  KeyQ: '[q]',
  KeyW: '[w]',
  KeyE: '[e]',
  KeyR: '[r]',
  KeyT: '[t]',
  KeyY: '[y]',
  KeyU: '[u]',
  KeyI: '[i]',
  KeyO: '[o]',
  KeyP: '[p]',
  BracketLeft: '[[]',
  BracketRight: '[]]',
  Enter: '[Return]',
  KeyA: '[a]',
  KeyS: '[s]',
  KeyD: '[d]',
  KeyF: '[f]',
  KeyG: '[g]',
  KeyH: '[h]',
  KeyJ: '[j]',
  KeyK: '[k]',
  KeyL: '[l]',
  Semicolon: '[Semicolon]',
  Quote: '[\']',
  Backquote: '[`]',
  Backslash: '[Backslash]',
  KeyZ: '[z]',
  KeyX: '[x]',
  KeyC: '[c]',
  KeyV: '[v]',
  KeyB: '[b]',
  KeyN: '[n]',
  KeyM: '[m]',
  Comma: '[,]',
  Period: '[.]',
  Slash: '[/]',
  NumpadMultiply: '[*]',
  Space: '[Space]',
  CapsLock: '[CapsLock]',
  F1: '[F1]',
  F2: '[F2]',
  F3: '[F3]',
  F4: '[F4]',
  F5: '[F5]',
  F6: '[F6]',
  F7: '[F7]',
  F8: '[F8]',
  F9: '[F9]',
  F10: '[F10]',
  NumLock: '[NumLock]',
  Numpad7: '[Num7]',
  Numpad8: '[Num8]',
  Numpad9: '[Num9]',
  NumpadSubtract: '[Num-]',
  Numpad4: '[Num4]',
  Numpad5: '[Num5]',
  Numpad6: '[Num6]',
  NumpadAdd: '[Num+]',
  Numpad1: '[Num1]',
  Numpad2: '[Num2]',
  Numpad3: '[Num3]',
  Numpad0: '[Num0]',
  NumpadDecimal: '[Num.]',
  F11: '[F11]',
  F12: '[F12]',
  IntlYen: '[jYen]',
  NumpadEqual: '[Num=]',
  NumpadEnter: '[NumEnter]',
  AudioVolumeMute: '[Mute]',
  AudioVolumeDown: '[Vol-]',
  AudioVolumeUp: '[Vol+]',
  NumpadComma: '[Num,]',
  NumpadDivide: '[Num/]',
  Home: '[Home]',
  ArrowUp: '[Up Arrow]',
  PageUp: '[PgUp]',
  ArrowLeft: '[Left Arrow]',
  ArrowRight: '[Right Arrow]',
  End: '[End]',
  ArrowDown: '[Down Arrow]',
  PageDown: '[PgDn]',
  Delete: '[Del]',
};

const windows = {
  Escape: '[Esc]',
  Digit1: '[1]',
  Digit2: '[2]',
  Digit3: '[3]',
  Digit4: '[4]',
  Digit5: '[5]',
  Digit6: '[6]',
  Digit7: '[7]',
  Digit8: '[8]',
  Digit9: '[9]',
  Digit0: '[0]',
  Minus: '[-]',
  Equal: '[=]',
  Backspace: '[Back]',
  Tab: '[Tab]',
  KeyQ: '[q]',
  KeyW: '[w]',
  KeyE: '[e]',
  KeyR: '[r]',
  KeyT: '[t]',
  KeyY: '[y]',
  KeyU: '[u]',
  KeyI: '[i]',
  KeyO: '[o]',
  KeyP: '[p]',
  BracketLeft: '[[]',
  BracketRight: '[]]',
  Enter: '[Return]',
  KeyA: '[a]',
  KeyS: '[s]',
  KeyD: '[d]',
  KeyF: '[f]',
  KeyG: '[g]',
  KeyH: '[h]',
  KeyJ: '[j]',
  KeyK: '[k]',
  KeyL: '[l]',
  Semicolon: '[Semicolon]',
  Quote: '[\']',
  Backquote: '[`]',
  Backslash: '[Backslash]',
  KeyZ: '[z]',
  KeyX: '[x]',
  KeyC: '[c]',
  KeyV: '[v]',
  KeyB: '[b]',
  KeyN: '[n]',
  KeyM: '[m]',
  Comma: '[,]',
  Period: '[.]',
  Slash: '[/]',
  NumpadMultiply: '[*]',
  Space: '[Space]',
  CapsLock: '[CapsLock]',
  F1: '[F1]',
  F2: '[F2]',
  F3: '[F3]',
  F4: '[F4]',
  F5: '[F5]',
  F6: '[F6]',
  F7: '[F7]',
  F8: '[F8]',
  F9: '[F9]',
  F10: '[F10]',
  NumLock: '[NumLock]',
  ScrollLock: '[ScrollLock]',
  Numpad7: '[Num7]',
  Numpad8: '[Num8]',
  Numpad9: '[Num9]',
  NumpadSubtract: '[Num-]',
  Numpad4: '[Num4]',
  Numpad5: '[Num5]',
  Numpad6: '[Num6]',
  NumpadAdd: '[Num+]',
  Numpad1: '[Num1]',
  Numpad2: '[Num2]',
  Numpad3: '[Num3]',
  Numpad0: '[Num0]',
  NumpadDecimal: '[Num.]',
  F11: '[F11]',
  F12: '[F12]',
  IntlYen: '[jYen]',
  NumpadEnter: '[NumEnter]',
  AudioVolumeMute: '[Mute]',
  AudioVolumeDown: '[Vol-]',
  AudioVolumeUp: '[Vol+]',
  NumpadDivide: '[Num/]',
  Home: '[Home]',
  ArrowUp: '[Up Arrow]',
  PageUp: '[PgUp]',
  ArrowLeft: '[Left Arrow]',
  ArrowRight: '[Right Arrow]',
  End: '[End]',
  ArrowDown: '[Down Arrow]',
  PageDown: '[PgDn]',
  Delete: '[Del]',
  OSLeft: '[L Win]',
  OSRight: '[R Win]',
};

export const keys = {
  '[Esc]': 'Esc',
  '[1]': '1',
  '[2]': '2',
  '[3]': '3',
  '[4]': '4',
  '[5]': '5',
  '[6]': '6',
  '[7]': '7',
  '[8]': '8',
  '[9]': '9',
  '[0]': '0',
  '[-]': '-',
  '[=]': '=',
  '[Back]': 'Bk',
  '[Tab]': 'Tab',
  '[TAB]': 'Tab',
  '[q]': 'Q',
  '[w]': 'W',
  '[e]': 'E',
  '[r]': 'R',
  '[t]': 'T',
  '[y]': 'Y',
  '[u]': 'U',
  '[i]': 'I',
  '[o]': 'O',
  '[p]': 'P',
  '[[]': '[',
  '[]]': ']',
  '[Return]': 'Rtn',
  '[a]': 'A',
  '[s]': 'S',
  '[d]': 'D',
  '[f]': 'F',
  '[g]': 'G',
  '[h]': 'H',
  '[j]': 'J',
  '[k]': 'K',
  '[l]': 'L',
  '[Semicolon]': ';',
  '[\']': '\'',
  '[`]': '`',
  '[Backslash]': 'Bkslash',
  '[z]': 'Z',
  '[x]': 'X',
  '[c]': 'C',
  '[v]': 'V',
  '[b]': 'B',
  '[n]': 'N',
  '[m]': 'M',
  '[,]': ',',
  '[.]': '.',
  '[/]': '/',
  '[*]': '*',
  '[Space]': 'Spce',
  '[CapsLock]': 'CapsLk',
  '[F1]': 'F1',
  '[F2]': 'F2',
  '[F3]': 'F3',
  '[F4]': 'F4',
  '[F5]': 'F5',
  '[F6]': 'F6',
  '[F7]': 'F7',
  '[F8]': 'F8',
  '[F9]': 'F9',
  '[F10]': 'F10',
  '[NumLock]': 'NumLk',
  '[ScrollLock]': 'ScrollLk',
  '[Num7]': 'Num7',
  '[Num8]': 'Num8',
  '[Num9]': 'Num9',
  '[Num-]': 'Num-',
  '[Num4]': 'Num4',
  '[Num5]': 'Num5',
  '[Num6]': 'Num6',
  '[Num+]': 'Num+',
  '[Num1]': 'Num1',
  '[Num2]': 'Num2',
  '[Num3]': 'Num3',
  '[Num0]': 'Num0',
  '[Num.]': 'Num.',
  '[F11]': 'F11',
  '[F12]': 'F12',
  '[jYen]': 'jKana',
  '[Num=]': 'Num=',
  '[NumEnter]': 'NumEnter',
  '[Mute]': 'Mute',
  '[Vol-]': 'Vol-',
  '[Vol+]': 'Vol+',
  '[Num,]': 'Num,',
  '[Num/]': 'Num/',
  '[Home]': 'webHome',
  '[Up Arrow]': 'Up',
  '[PgUp]': 'PgUp',
  '[Left Arrow]': 'Left',
  '[Right Arrow]': 'Rght',
  '[End]': 'End',
  '[Down Arrow]': 'Down',
  '[PgDn]': 'PgDn',
  '[Ins]': 'Ins',
  '[Del]': 'Del',
  '[L Win]': 'Win',
  '[R Win]': 'Win',
  '[Button 1]': 'MB1',
  '[Button 2]': 'MB2',
  '[Button 3]': 'MB3',
  '[Button 4]': 'MB4',
  '[Button 5]': 'MB5',
  '[Button 6]': 'MB6',
  '[Button 7]': 'MB7',
  '[Button 8]': 'MB8',
  '[<Unbound>]': '',
};

export const codes = os.platform() === 'win32' ? windows : mac;
